[package]
name = "balloon-software"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
tokio = { version = "1.0", features = ["full"] }

[target.'cfg(all(target_os = "linux", target_arch = "aarch64"))'.dependencies]
rppal = "0.22.1"
